#!/bin/bash

IMAGE_NAME="directorate-website"
CONTAINER_NAME="directorate-website-container"

# Paths to certificates generated by Certbot
CERT_PATH="/etc/letsencrypt/live/the-directorate.com/fullchain.pem"
KEY_PATH="/etc/letsencrypt/live/the-directorate.com/privkey.pem"

# Stop and remove old container if it exists
if [ "$(docker ps -aq -f name=$CONTAINER_NAME)" ]; then
    echo "Stopping and removing previous container ($CONTAINER_NAME)..."
    docker stop $CONTAINER_NAME
    docker rm $CONTAINER_NAME
fi

# Build the Docker image
echo "Building Docker image ($IMAGE_NAME)..."
docker image prune -f
docker build -t $IMAGE_NAME .

# Run the container, mounting certs
echo "Running new Docker container on ports 1000 and 1001 with SSL certs mounted..."
docker run -d -p 1000:80 -p 1001:443 \
    --name $CONTAINER_NAME \
    -v $CERT_PATH:/etc/nginx/certs/fullchain.pem:ro \
    -v $KEY_PATH:/etc/nginx/certs/privkey.pem:ro \
    $IMAGE_NAME

echo "Website deployment complete!"
